#!/usr/bin/env node

/**
 * Remote helper programs are invoked with one or (optionally) two arguments.
 * The first argument specifies a remote repository as in Git; it is either the name of a configured remote or a URL.
 * The second argument specifies a URL; it is usually of the form <transport>://<address>.
 * https://git-scm.com/docs/gitremote-helpers#_invocation
 */
if(process.argv.length < 2) {
  console.error('Usage: git-remote-igis remote-name url')
  process.exit(-10)
}

const readline = require('readline')
const Git = require('nodegit')
//const IPFS = require('ipfs')
const IPFSProxy = require('ipfs-http-client')
const all = require('it-all')
const toBuffer = require('it-to-buffer')
const OrbitDB = require('orbit-db')
const levelup = require('levelup')
const leveldown = require('leveldown')
const { Console } = require('console');
const fs = require('fs')

const EMPTY_REPO_CID = 'QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn'
const DEBUG = process.env.IGIS_DEBUG

const console = new Console(process.stderr)

const objForSig = (sig) => ({
  name: sig.name(), email: sig.email(),
  time: sig.when().time(), offset: sig.when().offset()
})

if(!process.env.GIT_DIR) {
  process.stderr.write('$GIT_DIR must be defined')
  process.exit(-9)
}

;(async () => {
  const cacheDir = `${process.env.GIT_DIR}/remote-igis`
  const repo = await Git.Repository.open(process.env.GIT_DIR)
  const odb = await repo.odb()
  const ipfs = IPFSProxy()
  const orbitdb = await OrbitDB.createInstance(
    ipfs, { directory: cacheDir }
  )
  const dbOptions = {
    //accessController: { write: [orbitdb.identity.id] },
    overwrite: true,
  }
  const cacheDB = await orbitdb.kvstore('igis:hash-cache', dbOptions)
  const refsDB = await orbitdb.kvstore('igis:repositories', dbOptions)

  process.stderr.write(`Loading: ${cacheDB.address}: `)
  await refsDB.load()
  await cacheDB.load()
  process.stderr.write('Done\n')

  const cache = {
    get: async (key) => {
      try {
        return cacheDB.get(key)
      } catch(err) {
        console.error(err)
      }
    },
    put: async (key, val) => {
      if(key && val) {
        return cacheDB.put(key, val, { pin: true }).catch(console.error)
      }
    },
  }

  // await fs.promises.mkdir(`${process.env.GIT_DIR}/remote-igis`, { recursive: true })
  //
  // const cacheDB = levelup(leveldown(cacheDir))  
  // const cache = {
  //   get: async (key) => {
  //     if(!process.env.IGIS_NO_CACHE) {
  //       try {
  //         return await cacheDB.get(key)
  //       } catch(err) { /* Not found */ }
  //     }
  //   },
  //   put: cacheDB.put.bind(cacheDB),
  // }

  const oidInODB = async (oid) => {
    try {
      return await odb.existsPrefix(oid, oid.length)
    } catch(err) {
      return false
    }
  }

  const treeFor = async (root, modesCID) => {
    DEBUG && console.debug('treeFor()', root)
    const list = await all(ipfs.ls(root))
    const tb = await Git.Treebuilder.create(repo, null)
    const modes = (await ipfs.dag.get(modesCID)).value

    await Promise.all(list.map(async ({ name, cid, type }) => {
      if(type === 'dir') {
        const tree = await treeFor(cid, modes[name])
        tb.insert(name, tree, Git.TreeEntry.FILEMODE.TREE)
      } else {
        let oid = await cache.get(cid)
        if(!oid || !(await oidInODB(oid.toString()))) {
          const buffer = await toBuffer(ipfs.cat(cid))
          oid = await odb.write(buffer.toString(), buffer.length, Git.Object.TYPE.BLOB)
          await cache.put(cid, oid) // if not awaited, the cache can close before this executes
        }
        tb.insert(name, oid, modes[name])
      }
    }))

    return tb.write()
  }

  const commitFor = async (cid) => {
    DEBUG && console.debug('commitFor()', cid)
    const root = (await ipfs.dag.get(cid)).value
    const { authorSig, committerSig, encoding, message, tree:treeCID, modes, parents:parentCIDs, signature } = root
    const tree = await Git.Tree.lookup(repo, await treeFor(treeCID, modes))
    console.debug(parentCIDs.length, 'parents')
    const parents = await Promise.all(parentCIDs.map(
      async c => await Git.Commit.lookup(repo, await commitFor(c))
    ))
    const parent_count = parents.length
    console.debug(parent_count, 'parents')
    const author = Git.Signature.create(authorSig.name, authorSig.email, authorSig.time, authorSig.offset)
    const committer = Git.Signature.create(committerSig.name, committerSig.email, committerSig.time, committerSig.offset)

    let commit
    if(signature) {
      const buffer = await Git.Commit.createBuffer(
        repo, author, committer, encoding, message, tree, parent_count, parents
      )
      commit = await Git.Commit.createWithSignature(repo, buffer.toString(), signature, 'gpgsig')
    } else {
      commit = await Git.Commit.create(
        repo, null, author, committer, encoding, message, tree, parent_count, parents
      )
    }
    process.stderr.write(`${commit} (${cid})\n`)
    return commit
  }

  const addTree = async (tree, path = '', base = EMPTY_REPO_CID) => {
    DEBUG && console.debug('addTree()', tree.id().toString())
    var modes = {}
    for(const e of (await tree.entries())) {
      if(e.isTree()) {
        DEBUG && console.debug('addTree() recursing')

        ;[base, sub] = await addTree(await e.getTree(), `${path}${e.name()}/`, base, modes)
        modes[e.name()] = sub
      } else if(e.filemode().toString(8)[0] === '1') { // e.isBlob() is false for links
        let cid = await cache.get(e.oid())
        if(!cid) {
          const content = (await e.getBlob()).content()
          const progress = (len) => process.stderr.write(`len:${len}\n`)

          DEBUG && console.debug('Adding', `${path}${e.name()}`)

          cid = (await all(ipfs.add({ content: content, progress: progress, pin: true })))[0].cid
          await cache.put(e.oid(), cid)
        }

        DEBUG && console.debug('Patching', `${path}${e.name()}`, cid.toString())
        base = await ipfs.object.patch.addLink(
          base, { name: `${path}${e.name()}`, cid: cid }, { create: true }
        )
        modes[e.name()] = e.filemode()
      } else {
        console.warn(`Neither Blob nor Tree TreeEntry: ${e.oid()} (${e.filemode().toString(8)})`)
      }
    }

    return [base, await ipfs.dag.put(modes)]
  }

  let oidMgr = {
    resolvers: {},
    convert: (oid) => {
      if(!oidMgr.resolvers[oid]) { // new
        addCommit(oid)
        oidMgr.resolvers[oid] = []
      }
      const promise = new Promise((res, rej) => {
        oidMgr.resolvers[oid].push(res)
      })
      return promise
    },
    cidFound: (oid, cid) => {
      if(oidMgr.resolvers[oid]) {
        while(oidMgr.resolvers[oid].length > 0) {
          oidMgr.resolvers[oid].pop().call(this, cid)
        }
      }
    }
  }

  const addCommit = async (oid) => {
    DEBUG && console.debug('addCommit()', oid.toString())
    process.stderr.write(`mit:${oid}: `)
    let cid = await cache.get(oid)
    if(cid) {
      cid = new IPFSProxy.CID(cid.toString())
      process.stderr.write(`cache:${cid}\n`)
    } else {
      const head = await Git.Commit.lookup(repo, oid)
      const [tree, modes] = await addTree(await head.getTree())
      process.stderr.write(`tree:${tree}\n`) // \r\x1b[A
      const parents = await Promise.all((await head.parents()).map(p => oidMgr.convert(p)))
      const obj = {
        authorSig: objForSig(head.author()), committerSig: objForSig(head.committer()),
        encoding: head.messageEncoding(), message: head.message(),
        parents: parents, tree: new IPFSProxy.CID(tree), modes: modes,
        oid: oid.toString(),
      }
      try {
        obj.signature = await head.headerField('gpgsig')
      } catch(err) { /* No signature */ }
      cid = await ipfs.dag.put(obj)
      await cache.put(oid.toString(), cid)
    }
    oidMgr.cidFound(oid, cid)
    return cid
  }

  const addTag = async (oid, name) => {
    let obj
    try {
      process.stderr.write(`tag:${oid}: `)
      const tag = await Git.Tag.lookup(repo, oid)
      const commit = await addCommit(tag.targetId())

      obj = {
        commit: commit, taggerSig: objForSig(tag.tagger()),
        name: name, message: tag.message(), type: 'annotated',
      }
    } catch(err) { // Lightweight tags return a commit instead of a tag
      const commit = await addCommit(oid)
      obj = {
        name: name, commit: commit, type: 'lightweight',
      }
    }
    return await ipfs.dag.put(obj)
  }

  const serializeRefs = async (root, path = 'refs') => {
    console.debug(root)
    await Promise.all(Object.entries(root).map(async ([name, obj]) => {
      console.debug(name, obj)
      if(obj instanceof IPFSProxy.CID) {
        serializeRefs(obj, `${path}/${name}`)
      } else {
        DEBUG && console.debug(`> ${root.oid} ${path}/${name}`)
        process.stdout.write(`${root.oid} ${path}/${name}\n`)
      }
    }))
  }

  const doFetch = async (url) => {
    console.debug('url', url)
    for(const [hash, ref] of [...new Set(fetchRefs)]) {
      DEBUG && console.debug('doFetch()', `${process.argv[3]}/.git/${ref}/cid`)
      const commit = await commitFor(refsDB.get(ref))
      await repo.createBranch(ref.replace(/^refs\/heads\//, ''), commit)
      console.debug(`Created Branch: ${ref.replace(/^refs\/heads\//, '')}`)
    }
    await repo.setHead(fetchRefs[0][1])
  }

  const doPush = async () => {
    let base, vfs = { oidcache: {} }
    while(pushRefs.length > 0) {
      const [src, dst] = pushRefs.shift()

      DEBUG && console.debug('doPush', src, dst)

      try {
        const oid = await Git.Reference.nameToId(repo, src)
        const isTag = dst.split('/')[1] === 'tags'
        DEBUG && console.debug('Starting w/ OID', oid.toString(), `(${src})`)
        const cid = await (isTag
          ? addTag(oid, dst.split('/').slice(2).join('/'))
          : addCommit(oid)
        )

        refsDB.put(dst, oid.toString())

        if(!base) {
          base = ((await ipfs.dag.get(`${cid}${isTag ? '/commit' : ''}`)).value).tree
        }
        if(!vfs.HEAD) {
          vfs.HEAD = dst
        }

        DEBUG && console.debug(`> ok ${dst}`)
        process.stdout.write(`ok ${dst}\n`)
      } catch(e) {
        console.error(e)
      }
    }
    try {
      vfs.refs = new IPFSProxy.CID((await refsDB.saveSnapshot())[0].hash)
      vfs.cache = new IPFSProxy.CID((await cacheDB.saveSnapshot())[0].hash)
    } catch(err) {
      console.error(err)
    }
    ipfs.pin.add(base)
    base = await ipfs.object.patch.addLink(
      base, { name: '.git', cid: await ipfs.dag.put(vfs) }, { create: true }
    )
    process.stderr.write(`igis::${base}\n`)
  }

  const rl = readline.createInterface({
    input: process.stdin, output: process.stdout, terminal: false,
  })
  const pushRefs = []
  const fetchRefs = []
  rl.on('line', async (line) => {
    DEBUG && console.debug('<', line)

    if(line === 'capabilities') {
      for(let option of ['options', 'push', 'fetch']) {
        DEBUG && console.debug(`> ${option}`)
        process.stdout.write(`${option}\n`)
      }
      process.stdout.write("\n")
    // } else if(line === 'list for-push') {
    //   let refs = await repo.getReferences()
    //   refs.filter(r => r.isBranch() || r.isTag()).forEach(
    //     r => {
    //       DEBUG && console.debug(`> 0000000000000000000000000000000000000000 ${r.name()}`)
    //       process.stdout.write(`0000000000000000000000000000000000000000 ${r.name()}\n`)
    //     }
    //   )
    //   process.stdout.write("\n")
    } else if(line.startsWith('list')) {
      if(line !== 'list for-push') {
        const branch = (await ipfs.dag.get(`${process.argv[3]}/.git/HEAD`)).value
        DEBUG && console.debug(`> @${branch} HEAD`)
        process.stdout.write(`@${branch} HEAD\n`)
      }
      for(const [ref, oid] of Object.entries(refsDB.index)) {
        DEBUG && console.debug(`> ${oid} ${ref}`)
        process.stdout.write(`${oid} ${ref}\n`)
      }
      process.stdout.write("\n")
    } else if(line.startsWith('push')) {
      try {
        const ref = line.replace(/^push\s+/, '')
        pushRefs.push(ref.split(':'))
      } catch(err) {
        console.error(`Can't Push: Invalid Refs: '${line}' (${err})\n`)
        process.exit(-12)
      }
    } else if(line.startsWith('fetch')) {
      const ref = line.replace(/^fetch\s+/, '')
      fetchRefs.push(ref.split(' '))
    } else if(line === '') { // a blank line follows a set of push/fetch commands
      const url = process.argv[2]
      if(pushRefs.length > 0) { 
        await doPush(url)
        DEBUG && console.debug('>')
        process.stdout.write("\n")
        cacheDB.close().catch(console.error)
      }
      if(fetchRefs.length > 0){ 
        await doFetch(url)
      }
    } else {
      console.debug(line)
    }
  })
})()