#!/usr/bin/env node

console.debug = (msg) => process.stderr.write(`${msg}\n`)

/**
 * Remote helper programs are invoked with one or (optionally) two arguments.
 * The first argument specifies a remote repository as in Git; it is either the name of a configured remote or a URL.
 * The second argument specifies a URL; it is usually of the form <transport>://<address>.
 * https://git-scm.com/docs/gitremote-helpers#_invocation
 */
if(process.argv.length < 2) {
  console.error('Usage: git-remote-igis remote-name url')
  process.exit(-10)
}

const readline = require('readline')
var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: true,
})

rl.on('line', async (line) => {
  switch(line) {
    case 'capabilities':
      console.debug('Capabilities Querried')
      process.stdout.write("push\n")
      process.stdout.write("fetch\n\n")
    break
    case 'list for-push':
      const Git = require('nodegit')
      const repo = await Git.Repository.open('.')
      console.debug('t')
    break
    default:
      console.debug(line)
  }
})
